### PR TITLE
switch hasNullOption to computed and add a slot to show custom value

### PR DESCRIPTION
**Pull request by schmurfy**
https://github.com/heyui/heyui/pull/135

### CODE REVIEW

**Comment by schmurfy** [comment]
I just noticed it was already done in dev so closing it.

**Comment by vvpvvp** [comment]
https://github.com/heyui/heyui/commit/c10b55de38e4af0fdde906463f4f65168f5d6801

**Comment by schmurfy** [comment]
thanks :)

**Comment by vvpvvp** [comment]
I should to thank you ,  hope more suggestions.

**Pull request closed without merging**
